# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-06 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191205_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=150),
            preserve_default=False,
        ),
    ]
