# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-06 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_subcategory_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='minicategory',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
