# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-22 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_minicategory_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minicategory',
            options={'ordering': ('name',), 'verbose_name': 'minicategory', 'verbose_name_plural': 'minicategories'},
        ),
    ]
